# Generated by Django 4.2.4 on 2023-08-18 20:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='Untitled Post', help_text="Your post's title...", max_length=128, validators=[django.core.validators.MinLengthValidator(1, 'Your must type at least 2 characters!')]),
        ),
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(help_text='Comment...', max_length=2048, validators=[django.core.validators.MinLengthValidator(1, 'Your must type at least 2 characters!')]),
        ),
        migrations.AlterField(
            model_name='post',
            name='text',
            field=models.TextField(help_text='Your post...', max_length=2048, validators=[django.core.validators.MinLengthValidator(2, 'Your must type at least 2 characters!')]),
        ),
    ]
